# Generated by Django 5.0.6 on 2024-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birth',
        ),
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='users', to='base.movie'),
        ),
    ]
